### ISSUE TITLE
How to use Numaker M2351 with mbedOS

### ISSUE THREAD

**Issue by BabaYB** [OpenNuvoton/NuMaker-mbed-TZ-secure-example#1]
I am wondering is there a manual to let me learn how to use Numaker M2351 with mbedOS, what drivers I need to install, and what`s the setup and so on?
I have tried to find something at here (http://www.nuvoton.com.cn/hq/products/microcontrollers/arm-cortex-m23-mcus/?__locale=zh), and I can use this board with Keil, but I want to develop it with mbedOS and gcc.
Thanks

**Comment by cyliangtw** [comment]
M2351 with mbedOS has some issue on building secure code @GCC, however ARM already fixed it and will patch into the next release, maybe 2019-q1 at https://developer.arm.com/open-source/gnu-toolchain/gnu-rm/downloads. 
So far, we only enable M2351 target for ARMCC (Keil compiler) and ARM tool team still in fixing online compiler for Cortex-M23.
For Kiel compiler, Nuvoton provide Free Keil at http://www2.keil.com/nuvoton.
Thus, in current stage, the feasible way is to use CLI with ARMCC (Keil compiler), CLI setup at:  https://os.mbed.com/docs/v5.10/tools/installation-and-setup.html .
For the simplest sample, you could refer to blinky example at: https://github.com/ARMmbed/mbed-os-example-blinky, follow the readme to build your 1st code, just replace K64F by NUMAKER_PFM_M2351 target.
For more details of general mbedos doc, you also could refer to https://os.mbed.com/docs/v5.10/ or issue your question in https://github.com/ARMmbed/mbed-os.

**Comment by BabaYB** [comment]
Hi, @cyliangtw , thanks for your help.
The problem I faced now is I can't get the mbed device used to drag and drop programming when NUMAKER_PFM_M2351 is plugged-in. And I have done this (https://os.mbed.com/docs/v5.10/tutorials/windows-serial-driver.html) to mount mbed driver.
Also, I used the command `mbed detect` but it didn't find the device. 
So what can I do for this problem next?
Yeah, and I used K64F before and it works well.
Thanks!

**Comment by cyliangtw** [comment]
Great, you have mbed experience on K64F and it will be easy to utilize mbed API on M2351.
Please set MSG switch (No.4 of ISW1 on ICE) to ON. (It maybe default at OFF position). ISW1 is nearby usb port.
Then, please follow https://os.mbed.com/platforms/NUMAKER-PFM-M2351/ board page, to install `Windows serial port driver`. More, you also could see the ISW1 picture in `Upgrade Procedure` section of this web page.

**Comment by BabaYB** [comment]
Yes! I think this is what I want, I will do this soon.
Thank you very much.

**Comment by BabaYB** [comment]
Hi, I found that the MSG switch is OFF in the picture in `Upgrade Procedure` section. Please check it.
And you can close this issue now.
Thanks for your help!

**Comment by cyliangtw** [comment]
Thanks, we will review the picture to avoid confusion.
